### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by johnd0e** [Avadhkumar-geek/StudentAI#5]
I see only this response:
'Something went wrong!! Please, try again later.'

**Comment by Avadhkumar-geek** [comment]
> I see only this response:
> 'Something went wrong!! Please, try again later.'

API used in this app is no longer maintained or down. You can use the official OpenAI API.

**Comment by johnd0e** [comment]
Could you implement custom API endpoint setting?

**Comment by Avadhkumar-geek** [comment]
> Could you implement custom API endpoint setting?

I don't have the time at the moment; simply change the API in the code.
